---
# CONFIGURAZIONE IDENTITY PROVIDER

# URL da usare per generare l'entityID dell'IdP e gli URL degli endpoint
# SAML indicati nel metadata dell'IdP
base_url: "https://spid-idp.example:8443"

# Chiave e certificato necessari per la firma dei messaggi SAML
key_file: "./conf/spid-idp.key.pem"
cert_file: "./conf/spid-idp.cert.pem"


# CONFIGURAZIONE SERVICE PROVIDER

# Si possono configurare più Service Provider. Per leggere i metadati da un 
# file .xml è sufficiente inserirne il path sotto "local"; per leggerli da 
# un URL remoto bisogna invece inserirlo sotto "remote" (insieme al path di
# una copia locale del certificato del Service Provider, che per sicurezza 
# deve coincidere con quello presente nei metadati).
# cfr. https://pysaml2.readthedocs.io/en/latest/howto/config.html#metadata
metadata:
  local:
  - "./conf/iam.local.io.metadata.xml"

# CONFIGURAZIONE TESTENV WEB SERVER

# Abilita (true) o disabilita (false) la modalità debug
debug: true

# Indirizzo IP dell'interfaccia su cui esporre il server e porta
# (0.0.0.0 per ascoltare su tutte le interfacce)
host: 0.0.0.0
port: 8443

# Abilita (true) o disabilita (false) la modalità HTTPS per l'IdP
https: true

# Se si abilita HTTPS è necessario specificare chiave e certificato
# (indipendenti da chiave e certificato SAML)
https_key_file: "./conf/spid_idp_example.key.pem"
https_cert_file: "./conf/spid_idp_example.cert.pem"

# Endpoint del server IdP (path relativi)
endpoints:
  single_sign_on_service: "/sso"
  single_logout_service: "/slo"

# Abilita (true) o disabilita (false) la possibilità di aggiungere nuovi utenti
can_add_user: true
