version: '3'

volumes:
  dbdata:
  trustanchors:
  cabundle:

services:

  db:
    container_name: db
    image: mariadb
    volumes:
      - dbdata:/var/lib/mysql
  
    environment:
      TZ: Europe/Rome
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_USER: iam
      MYSQL_PASSWORD: pwd
      MYSQL_DATABASE: iam

    ports:
      - "3306:3306"

  iam-db-deploy:
    container_name: iam-be
    image: cloud-vm114.cloud.cnaf.infn.it/indigoiam/iam-login-service:v1.5.0.rc0-latest

    environment:
      TZ: Europe/Rome
      IAM_JAVA_OPTS: -Dspring.profiles.active=mysql-test

      IAM_HOST: iam.local.io
      IAM_BASE_URL: https://iam.local.io
      IAM_ISSUER: https://iam.local.io
      IAM_USE_FORWARDED_HEADERS: "true"
      IAM_NOTIFICATION_DISABLE: "true"

      IAM_DB_HOST: db
      IAM_DB_USERNAME: iam
      IAM_DB_PASSWORD: pwd

    volumes:
      - trustanchors:/etc/grid-security/certificates

  trust:
    image: indigoiam/trustanchors
    volumes:
      - trustanchors:/etc/grid-security/certificates
      - cabundle:/etc/pki

  iam:
    image: indigoiam/nginx
    dns_search: local.io
    container_name: iam

    environment:
      TZ: Europe/Rome
      NGINX_HOST: iam
      NGINX_PORT: 443

    ports:
      - "443:443"

    volumes:
      - /dev/urandom:/dev/random
      - ./assets/iam.conf:/etc/nginx/conf.d/default.conf:ro

    networks:
      default:
        aliases:
          - iam.local.io
